// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:2b189791-fc34-4df3-8605-1af84870a8e3',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'wealthloveride-hosting-mobilehub-88811044',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dyzh2jhfnqhd1.cloudfront.net',
    'aws_mobile_analytics_app_id': '931fe5b8001440f28512211134a5082c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ba582282-c00d-48a7-9ce8-3615f2d3a292',
    'aws_project_name': 'Wealth.LoveRide',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'wealthloveride-mobilehub-88811044',
}

export default awsmobile;
